"""Add soft delete columns

Revision ID: 56cc387c0d88
Revises: 47eb24df6a66
Create Date: 2025-05-17 18:05:39.962639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cc387c0d88'
down_revision: Union[str, None] = '47eb24df6a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    op.drop_column('transactions', 'deleted')
    # ### end Alembic commands ###
